version: '3'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SELENIUM_FIREFOX_URL=http://selenium-firefox:4444/wd/hub
      - SELENIUM_FIREFOX_PROFILE=/tmp/firefox-profile
      - SELENIUM_CHROME_URL=http://selenium-chrome:4444/wd/hub
      - SELENIUM_CHROME_PROFILE=/tmp/chrome-profile

  selenium-firefox:
    image: selenium/standalone-firefox
    ports:
      - 7900:7900
    volumes:
      - firefox-profile:/tmp/firefox-profile
    depends_on:
      - init-selenium-firefox

  init-selenium-firefox:
    image: busybox
    command:
      - sh
      - -c
      - chown -R 1200:1201 /tmp/firefox-profile
    volumes:
      - firefox-profile:/tmp/firefox-profile

  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - 7901:7900
    volumes:
      - chrome-profile:/tmp/chrome-profile
    depends_on:
      - init-selenium-chrome

  init-selenium-chrome:
    image: busybox
    command:
      - sh
      - -c
      - chown -R 1200:1201 /tmp/chrome-profile
    volumes:
      - chrome-profile:/tmp/chrome-profile

  playwright-chromium:
    build:
      context: .
      dockerfile: Dockerfile.playwright-chromium
    environment:
      - PLAYWRIGHT_BROWSER=chromium
      - PLAYWRIGHT_PORT=3000
    ports:
      - "3000:3000"

  playwright-firefox:
    build:
      context: .
      dockerfile: Dockerfile.playwright-firefox
    environment:
      - PLAYWRIGHT_BROWSER=firefox
      - PLAYWRIGHT_PORT=3002
    ports:
      - "3002:3002"

  playwright-webkit:
    build:
      context: .
      dockerfile: Dockerfile.playwright-webkit
    environment:
      - PLAYWRIGHT_BROWSER=webkit
      - PLAYWRIGHT_PORT=3003
    ports:
      - "3003:3003"

volumes:
  firefox-profile:
  chrome-profile:
