# generate.jq -- validate the gateway endpoint registry and render the nginx
# config and the UI's endpoint list from it.
#
# Usage (see gateway/entrypoint.sh):
#   jq -e -f generate.jq \
#     --arg resolver "$GATEWAY_RESOLVER" \
#     --arg base "$GATEWAY_BASE_PATH" \
#     --arg suffix "$GATEWAY_UPSTREAM_SUFFIX" \
#     --arg pw "$GATEWAY_PW_SESSION" \
#     --arg se "$GATEWAY_SE_SESSION" \
#     --arg rundir "$GATEWAY_RUN_DIR" \
#     registry.json
#
# Input : the registry as JSON ({"endpoints": [...]}).
# Output: {"nginx": "<default.conf>",
#          "endpoints": {"endpoints": [{id,label,framework,browser,node,storage_state}]}}
#
# Validation is fail-closed: the first problem calls error() (non-zero exit,
# message on stderr) and no output is produced. The noVNC upstream is never
# exposed in "endpoints" (the browser only needs the session-manager API).

def fail($m): error($m);

def has_newline: test("[\\n\\r]");

def frameworks: ["playwright", "selenium"];

# Validate the env-derived arguments. Rejects nginx metacharacters before any
# value reaches a directive. The base path is also checked in the entrypoint
# for an early message; this keeps a direct jq invocation fail-closed too.
def validate_args($resolver; $b; $sfx; $pw; $se; $rundir):
  if ($resolver | has_newline) then fail("invalid resolver: \($resolver)")
  elif ($resolver | test("^[A-Za-z0-9.:\\[\\]]+$") | not) then fail("invalid resolver: \($resolver)")
  elif ($b | has_newline) then fail("invalid base path: \($b)")
  elif ($b | test("^(/[A-Za-z0-9-]+)*$") | not) then fail("invalid base path: \($b)")
  elif ($sfx | has_newline) then fail("invalid upstream suffix: \($sfx)")
  elif ($sfx | test("^$|^\\.[A-Za-z0-9._-]+$") | not) then fail("invalid upstream suffix: \($sfx)")
  elif ($pw | has_newline) then fail("invalid playwright session upstream: \($pw)")
  elif ($pw | test("^[A-Za-z0-9._-]+$") | not) then fail("invalid playwright session upstream: \($pw)")
  elif ($se | has_newline) then fail("invalid selenium session upstream: \($se)")
  elif ($se | test("^[A-Za-z0-9._-]+$") | not) then fail("invalid selenium session upstream: \($se)")
  elif ($rundir | test("^/[A-Za-z0-9._/-]+$") | not) then fail("invalid run dir: \($rundir)")
  else . end;

def header:
  "# Generated by gateway/generate.jq from the endpoint registry.\n" +
  "# Do not edit: it is overwritten at container start.\n";

def root_redir($b):
  if $b == "" then empty
  else "    location = / {\n        return 308 \($b)/;\n    }"
  end;

def ui_loc($b):
  if $b == "" then empty
  else "    location \($b)/ {\n        alias /usr/share/nginx/html/;\n        index index.html;\n    }"
  end;

# One shared location for every full-size view; the browser URL is kept and
# view.html derives the id from location.pathname.
def view_loc($b):
  "    location \($b)/view/ {\n        rewrite ^\($b)/view/.*$ \($b)/view.html last;\n    }";

def api_loc($b; $pw; $se; $sfx; $rundir):
  (
    "    location = \($b)/api/endpoints {\n        alias \($rundir)/endpoints.json;\n        default_type application/json;\n        add_header Cache-Control \"no-store\" always;\n    }",
    "    location \($b)/api/playwright/ {\n        set $pw_sessions \($pw)\($sfx):8081;\n        rewrite ^\($b)/api/playwright/(.*) /api/playwright/$1 break;\n        proxy_pass http://$pw_sessions;\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_read_timeout 150s;\n    }",
    "    location \($b)/api/selenium/ {\n        set $se_sessions \($se)\($sfx):8082;\n        rewrite ^\($b)/api/selenium/(.*) /api/selenium/$1 break;\n        proxy_pass http://$se_sessions;\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_read_timeout 150s;\n    }"
  );

# Raw noVNC per endpoint. The first rewrite serves the noVNC page for the
# directory root; the second forwards assets and the websocket path.
def novnc_loc($b; $sfx; $e):
  "    location \($b)/vnc/\($e.id)/ {\n        set $novnc_node \($e.host)\($sfx):\($e.port);\n        rewrite ^\($b)/vnc/\($e.id)/$ /vnc.html break;\n        rewrite ^\($b)/vnc/\($e.id)/(.*) /$1 break;\n        proxy_pass http://$novnc_node;\n        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection $connection_upgrade;\n        proxy_set_header Host $host;\n        proxy_read_timeout 1d;\n    }";

def norm($i):
  if type != "object" then fail("endpoints[\($i)]: must be a mapping") else . end
  | (keys_unsorted - ["id", "label", "framework", "browser", "node", "storage_state", "novnc"]) as $unk
  | if ($unk | length) > 0 then fail("endpoints[\($i)]: unknown keys: \($unk | join(", "))") else . end
  | (.id) as $id
  | if ($id | type) != "string" then fail("endpoints[\($i)]: id must be a string")
    elif ($id | test("^[a-z0-9-]+$") | not) then fail("endpoints[\($i)]: invalid id \($id) (want ^[a-z0-9-]+$)")
    elif ($id | length) > 63 then fail("endpoints[\($i)]: id too long (max 63)")
    else . end
  | (.label) as $label
  | if ($label | type) != "string" or ($label | length) == 0 then fail("endpoints[\($i)] (\($id)): label must be a non-empty string")
    elif ($label | contains("\n")) or ($label | contains("\r")) then fail("endpoints[\($i)] (\($id)): label must not contain newlines")
    elif ($label | length) > 64 then fail("endpoints[\($i)] (\($id)): label too long (max 64)")
    else . end
  | (.framework) as $framework
  | if ($framework | type) != "string" then fail("endpoints[\($i)] (\($id)): framework must be a string")
    elif (frameworks | index($framework)) == null then fail("endpoints[\($i)] (\($id)): unknown framework \($framework) (known: \(frameworks | join(", ")))")
    else . end
  | (.browser) as $browser
  | if ($browser | type) != "string" or ($browser | length) == 0 then fail("endpoints[\($i)] (\($id)): browser must be a non-empty string")
    else . end
  | (.node) as $node
  | if ($node != null) and (($node | type) != "string" or ($node | test("^[A-Za-z0-9._-]+$") | not)) then fail("endpoints[\($i)] (\($id)): node must be null or match ^[A-Za-z0-9._-]+$")
    else . end
  | (.novnc) as $n
  | if ($n | type) != "object" then fail("endpoints[\($i)] (\($id)): novnc is required and must be a mapping") else . end
  | ($n | keys_unsorted - ["host", "port"]) as $nunk
  | if ($nunk | length) > 0 then fail("endpoints[\($i)] (\($id)): unknown novnc keys: \($nunk | join(", "))") else . end
  | ($n.host) as $host
  | if ($host | type) != "string" then fail("endpoints[\($i)] (\($id)): novnc.host must be a string")
    elif ($host | test("^[A-Za-z0-9._-]+$") | not) then fail("endpoints[\($i)] (\($id)): novnc.host must match ^[A-Za-z0-9._-]+$")
    else . end
  | ($n.port // 7900) as $port
  | if ($port | type) != "number" then fail("endpoints[\($i)] (\($id)): novnc.port must be an integer 1-65535")
    elif (($port | floor) != $port) or ($port < 1) or ($port > 65535) then fail("endpoints[\($i)] (\($id)): novnc.port must be an integer 1-65535")
    else . end
  | (.storage_state // false) as $ss
  | if ($ss | type) != "boolean" then fail("endpoints[\($i)] (\($id)): storage_state must be a boolean")
    elif ($ss == true) and ($framework != "playwright") then fail("endpoints[\($i)] (\($id)): storage_state is only supported for playwright")
    else . end
  | {id: $id, label: $label, framework: $framework, browser: $browser, node: $node, host: $host, port: $port, storage_state: $ss};

. as $root
| validate_args($resolver; $base; $suffix; $pw; $se; $rundir)
| if ($root | type) != "object" then fail("registry: must be a mapping") else . end
| ($root | keys_unsorted - ["endpoints"]) as $runk
| if ($runk | length) > 0 then fail("registry: unknown keys: \($runk | join(", "))") else . end
| ($root.endpoints) as $eps
| if ($eps | type) != "array" then fail("registry: 'endpoints' must be an array")
  elif ($eps | length) == 0 then fail("registry: 'endpoints' must not be empty")
  else . end
| [ $eps | to_entries[] | .key as $i | .value | norm($i) ] as $E
| ($E | map(.id)) as $ids
| if ($ids | length) != ($ids | unique | length) then fail("registry: duplicate endpoint id") else . end
| ($E | map([.framework, .browser, .node])) as $uniq
| if ($uniq | length) != ($uniq | unique | length) then fail("registry: duplicate (framework, browser, node)") else . end
| {
    nginx: (
      header
      + "resolver \($resolver) valid=10s ipv6=off;\n\n"
      + "map $http_upgrade $connection_upgrade {\n    default upgrade;\n    ''      close;\n}\n\n"
      + "server {\n"
      + "    listen 80;\n"
      + "    root /usr/share/nginx/html;\n"
      + "    index index.html;\n\n"
      + "    location = /healthz {\n        access_log off;\n        return 200 \"ok\\n\";\n    }\n\n"
      + ([
          root_redir($base),
          ui_loc($base),
          view_loc($base),
          api_loc($base; $pw; $se; $suffix; $rundir),
          ($E[] | novnc_loc($base; $suffix; .))
        ] | join("\n"))
      + "\n}\n"
    ),
    endpoints: {endpoints: [$E[] | {id, label, framework, browser, node, storage_state}]}
  }
